// <auto-generated />
namespace HotelsA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class restuorantorderbookingbookingdetailmodelsareadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(restuorantorderbookingbookingdetailmodelsareadd));
        
        string IMigrationMetadata.Id
        {
            get { return "201909151403106_restuorantorder+booking+bookingdetailmodelsareadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
